import { HorizonTabsHomeProps } from "@/components/HorizonTabsHome/HorizonTabsHome";
import DS4 from "../public/src/4.jpg";
import DS17 from "../public/src/17.jpg";
import DS18 from "../public/src/18.jpg";
import DS32 from "../public/src/32.jpg";
import DS36 from "../public/src/36.jpg";
import DS37 from "../public/src/37.jpg";

const data: HorizonTabsHomeProps[] = [
  {
    id: 1,
    label: `RN-65HD-i5-256G8`,
    price: 250000,
    description: "Основные характеристики модели RN-65HD-i5-256G8",
    content: DS4,
    tabLink: "/RN-65HD-i5-256G8",
    specifications: [
      { label: "Диагональ", value: "65 дюймов" },
      { label: "Тип подсветки", value: "D-LED" },
      { label: "Разрешение", value: "3840х2160 (4K Ultra HD)" },
      { label: "Контрастность", value: "3000:1" },
      { label: "Жизненный цикл", value: "≥50,000 ч" },
      { label: "Тип сенсора", value: "Инфракрасный сенсорный экран" },
      { label: "ОС (опционально)", value: "Android 11/13/14" },
      { label: "Объем внутренней памяти", value: "32G/128G/256G" },
      { label: "Размер панели", value: "1488x906x87 мм" },
      { label: "Процессор", value: "Intel Core i5-12450H (4.4 Ггц, 8 ядер 12 потоков)" },
      { label: "Оперативная память", value: "8Gb/16Gb/32Gb" },
    ],
  },
  {
    id: 2,
    label: "RN-65HD-i7-512G16",
    price: 300000,
    description: "Основные характеристики модели RN-65HD-i7-512G16",
    content: DS17,
    tabLink: "/RN-65HD-i7-512G16",
    specifications: [
      { label: "Диагональ", value: "65 дюймов" },
      { label: "Тип подсветки", value: "D-LED" },
      { label: "Разрешение", value: "3840х2160 (4K Ultra HD)" },
      { label: "Контрастность", value: "3000:1" },
      { label: "Жизненный цикл", value: "≥50,000 ч" },
      { label: "Тип сенсора", value: "Инфракрасный сенсорный экран" },
      { label: "ОС (опционально)", value: "Android 11/13/14" },
      { label: "Объем внутренней памяти", value: "32G/128G/256G" },
      { label: "Размер панели", value: "1488x906x87 мм" },
      { label: "Процессор", value: "Intel Core i7-13620H (4.9 Ггц, 10 ядер 16 потоков)" },
      { label: "Оперативная память", value: "8Gb/16Gb/32Gb" },
    ],
  },
  {
    id: 3,
    label: "RN-75HD-i5-256G",
    price: 300000,
    description: "Основные характеристики модели RN-75HD-i5-256G",
    content: DS18,
    tabLink: "/RN-75HD-i5-256G",
    specifications: [
      { label: "Диагональ", value: "75 дюймов" },
      { label: "Тип подсветки", value: "D-LED" },
      { label: "Разрешение", value: "3840х2160 (4K Ultra HD)" },
      { label: "Контрастность", value: "5000:1" },
      { label: "Жизненный цикл", value: "≥50,000 ч" },
      { label: "Тип сенсора", value: "Инфракрасный сенсорный экран" },
      { label: "ОС (опционально)", value: "Android 11/13/14" },
      { label: "Объем внутренней памяти", value: "32G/128G/256G" },
      { label: "Размер панели", value: "1709x1038x90 мм" },
      { label: "Процессор", value: "Intel Core i5-12450H (4.4 Ггц, 8 ядер 12 потоков)" },
      { label: "Оперативная память", value: "8Gb/16Gb/32Gb" },
    ],
  },
  {
    id: 4,
    label: "RN-75HD-i7-512G",
    price: 350000,
    description: "Основные характеристики модели RN-75HD-i7-512G",
    content: DS32,
    tabLink: "/RN-75HD-i7-512G",
    specifications: [
      { label: "Диагональ", value: "75 дюймов" },
      { label: "Тип подсветки", value: "D-LED" },
      { label: "Разрешение", value: "3840х2160 (4K Ultra HD)" },
      { label: "Контрастность", value: "5000:1" },
      { label: "Жизненный цикл", value: "≥50,000 ч" },
      { label: "Тип сенсора", value: "Инфракрасный сенсорный экран" },
      { label: "ОС (опционально)", value: "Android 11/13/14" },
      { label: "Объем внутренней памяти", value: "32G/128G/256G" },
      { label: "Размер панели", value: "1709x1038x90 мм" },
      { label: "Процессор", value: "Intel Core i7-13620H (4.9 Ггц, 10 ядер 16 потоков)" },
      { label: "Оперативная память", value: "8Gb/16Gb/32Gb" },
    ],
  },
  {
    id: 5,
    label: "RN-86HD-i5-256G",
    price: 350000,
    description: "Основные характеристики модели RN-86HD-i5-256G",
    content: DS36,
    tabLink: "RN-86HD-i5-256G",
    specifications: [
      { label: "Диагональ", value: "86 дюймов" },
      { label: "Тип подсветки", value: "D-LED" },
      { label: "Разрешение", value: "3840х2160 (4K Ultra HD)" },
      { label: "Контрастность", value: "5000:1" },
      { label: "Жизненный цикл", value: "≥50,000 ч" },
      { label: "Тип сенсора", value: "Инфракрасный сенсорный экран" },
      { label: "ОС (опционально)", value: "Android 11/13/14" },
      { label: "Объем внутренней памяти", value: "32G/128G/256G" },
      { label: "Размер панели", value: "1954x1138x88 мм" },
      { label: "Процессор", value: "Intel Core i5-12450H (4.4 Ггц, 8 ядер 12 потоков)" },
      { label: "Оперативная память", value: "8Gb/16Gb/32Gb" },
    ],
  },
  {
    id: 6,
    label: "RN-86HD-i7-512G",
    price: 400000,
    description: "Основные характеристики модели RN-86HD-i7-512G",
    content: DS37,
    tabLink: "/RN-86HD-i7-512G",
    specifications: [
      { label: "Диагональ", value: "86 дюймов" },
      { label: "Тип подсветки", value: "D-LED" },
      { label: "Разрешение", value: "3840х2160 (4K Ultra HD)" },
      { label: "Контрастность", value: "5000:1" },
      { label: "Жизненный цикл", value: "≥50,000 ч" },
      { label: "Тип сенсора", value: "Инфракрасный сенсорный экран" },
      { label: "ОС (опционально)", value: "Android 11/13/14" },
      { label: "Объем внутренней памяти", value: "32G/128G/256G" },
      { label: "Размер панели", value: "1954x1138x88 мм" },
      { label: "Процессор", value: "Intel Core i7-13620H (4.9 Ггц, 10 ядер 16 потоков)" },
      { label: "Оперативная память", value: "8Gb/16Gb/32Gb" },
    ],
  },
];

export default data;
